# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import heartbeat_pb2 as heartbeat__pb2


class HearBeatStub(object):
  """The greeting service definition.
  """

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.getStatus = channel.unary_unary(
        '/HearBeat/getStatus',
        request_serializer=heartbeat__pb2.HeartBeatRequest.SerializeToString,
        response_deserializer=heartbeat__pb2.HeartBeatResponse.FromString,
        )


class HearBeatServicer(object):
  """The greeting service definition.
  """

  def getStatus(self, request, context):
    """Sends a greeting
    """
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_HearBeatServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'getStatus': grpc.unary_unary_rpc_method_handler(
          servicer.getStatus,
          request_deserializer=heartbeat__pb2.HeartBeatRequest.FromString,
          response_serializer=heartbeat__pb2.HeartBeatResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'HearBeat', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
