# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: payload.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='payload.proto',
  package='route',
  syntax='proto3',
  serialized_options=_b('H\001P\001'),
  serialized_pb=_b('\n\rpayload.proto\x12\x05route\"g\n\x05Route\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0e\n\x06origin\x18\x02 \x01(\x03\x12\x13\n\x0b\x64\x65stination\x18\x03 \x01(\x03\x12\x0e\n\x06seqnum\x18\x04 \x01(\x03\x12\x0c\n\x04path\x18\x05 \x01(\t\x12\x0f\n\x07payload\x18\x06 \x01(\x0c\x32l\n\x0cRouteService\x12\'\n\x07request\x12\x0c.route.Route\x1a\x0c.route.Route\"\x00\x12\x33\n\x11requestStreamFrom\x12\x0c.route.Route\x1a\x0c.route.Route\"\x00\x30\x01\x42\x04H\x01P\x01\x62\x06proto3')
)




_ROUTE = _descriptor.Descriptor(
  name='Route',
  full_name='route.Route',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='route.Route.id', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='origin', full_name='route.Route.origin', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='destination', full_name='route.Route.destination', index=2,
      number=3, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='seqnum', full_name='route.Route.seqnum', index=3,
      number=4, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='path', full_name='route.Route.path', index=4,
      number=5, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='payload', full_name='route.Route.payload', index=5,
      number=6, type=12, cpp_type=9, label=1,
      has_default_value=False, default_value=_b(""),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=24,
  serialized_end=127,
)

DESCRIPTOR.message_types_by_name['Route'] = _ROUTE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Route = _reflection.GeneratedProtocolMessageType('Route', (_message.Message,), dict(
  DESCRIPTOR = _ROUTE,
  __module__ = 'payload_pb2'
  # @@protoc_insertion_point(class_scope:route.Route)
  ))
_sym_db.RegisterMessage(Route)


DESCRIPTOR._options = None

_ROUTESERVICE = _descriptor.ServiceDescriptor(
  name='RouteService',
  full_name='route.RouteService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=129,
  serialized_end=237,
  methods=[
  _descriptor.MethodDescriptor(
    name='request',
    full_name='route.RouteService.request',
    index=0,
    containing_service=None,
    input_type=_ROUTE,
    output_type=_ROUTE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='requestStreamFrom',
    full_name='route.RouteService.requestStreamFrom',
    index=1,
    containing_service=None,
    input_type=_ROUTE,
    output_type=_ROUTE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_ROUTESERVICE)

DESCRIPTOR.services_by_name['RouteService'] = _ROUTESERVICE

# @@protoc_insertion_point(module_scope)
